#!/usr/bin/env python3
"""Generate the site's machine-readable indexes, and check the pages agree.

    makeMeta.py            write blog.html's JSON-LD block and sitemap.xml
    makeMeta.py --check    exit 1 if either is out of date, write nothing

Source of truth is the same one the feeds use: the <ul class="posts"> list in
rootdomain/personal/blog.html, parsed by makeFeed.parse_posts. Three artifacts
are derived from it here:

  1. The "blogPost" array of the Blog node in blog.html's JSON-LD, generated
     between the blogld:start/end markers. The markers sit OUTSIDE the
     <script> because JSON has no comment syntax, so the whole block is
     rewritten rather than a region inside it.

  2. rootdomain/sitemap.xml.

  3. Nothing — the third job is CHECKS, not artifacts: each post page
     carries its own dateline and its own BlogPosting node, and both must
     agree with the list. Those are hand-written, because a post page is
     hand-written; a generator that reached into six files to fix up dates
     would be solving the wrong problem. Disagreement is an error. Every JSON-LD
     block on the site must also parse, and every @id it references must be
     defined somewhere — see check_graph for why nothing else can catch that.

Adding a post therefore stays the one-line edit to blog.html that feeds.txt
advertises, plus the post file itself. See siteAssets.txt and feeds.txt.

Output is deterministic — no clock anywhere — for the same reason makeFeed's
is: the pre-commit hook regenerates and re-stages these, and a timestamp would
put a diff in every commit and fight the working tree forever.
"""

import json
import re
import sys
from pathlib import Path

from makeFeed import BASE, SITE, PostError, parse_posts

ROOT = Path(__file__).resolve().parent.parent
PERSONAL = ROOT / "rootdomain" / "personal"
BLOG = PERSONAL / "blog.html"
OUT_SITEMAP = ROOT / "rootdomain" / "sitemap.xml"

ROBIN = {"@id": f"{SITE}/professional/#robin"}
WEBSITE = {"@id": f"{SITE}/#website"}
BLOG_URL = f"{BASE}blog.html"
BLOG_ID = f"{BLOG_URL}#blog"

START = ('  <!-- blogld:start GENERATED by assetsBuild/makeMeta.py from '
         '<ul class="posts"> - do not edit -->')
END = "  <!-- blogld:end -->"

# Pages that are not blog posts. lastmod is deliberately ABSENT for all of
# them: it is optional in the sitemap protocol, consumers discount a lastmod
# they can catch being wrong, and this repo has no honest source for one on
# these files. The old hand-written sitemap claimed 2026-08-27 for six URLs
# and had been wrong about most of them for a while. The blog posts below DO
# get one, because there it is a real date the site states out loud.
STATIC = [
    (f"{SITE}/", None),
    (f"{SITE}/professional/", None),
    (f"{SITE}/professional/status", "always"),
    (f"{SITE}/resume.pdf", None),
    (f"{BASE}", None),
    (f"{BLOG_URL}", None),
    (f"{BASE}ntpuserinfo.html", None),
]


def blog_ld(posts):
    """The whole JSON-LD graph for blog.html.

    The CollectionPage and the Blog's own descriptive properties are constants
    here rather than in the page, because the block is generated wholesale —
    see the module docstring for why it cannot be a region inside the script.
    """
    graph = [
        {
            "@type": "CollectionPage",
            "@id": BLOG_URL,
            "url": BLOG_URL,
            "name": "blog — robin’s page",
            "inLanguage": "en",
            "isPartOf": WEBSITE,
            "mainEntity": {"@id": BLOG_ID},
        },
        {
            "@type": "Blog",
            "@id": BLOG_ID,
            "url": BLOG_URL,
            "name": "robin’s blog",
            "description": "the least consistent blog on the W3",
            "inLanguage": "en",
            "isPartOf": WEBSITE,
            "author": ROBIN,
            "publisher": ROBIN,
            "blogPost": [
                {
                    "@type": "BlogPosting",
                    "@id": p["url"] + "#post",
                    "url": p["url"],
                    "headline": p["title"],
                    "datePublished": p["published"],
                    "dateModified": p["updated"],
                }
                for p in posts
            ],
        },
    ]
    body = json.dumps({"@context": "https://schema.org", "@graph": graph},
                      ensure_ascii=False, indent=2)
    # Collapse the single-key @id references onto one line, matching the style
    # of the hand-written blocks on the other pages.
    while True:
        collapsed = re.sub(r'\{\n\s*("@id": "[^"]*")\n\s*\}',
                           lambda m: "{ %s }" % m.group(1), body)
        if collapsed == body:
            break
        body = collapsed
    body = "\n".join("  " + l if l else l for l in body.split("\n"))
    return "\n".join([START,
                      '  <script type="application/ld+json">',
                      body,
                      "  </script>",
                      END])


def sitemap(posts):
    out = ['<?xml version="1.0" encoding="UTF-8"?>', "",
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">', ""]
    entries = list(STATIC) + [(p["url"], p["updated"]) for p in posts]
    for loc, extra in entries:
        out += ["  <url>", f"    <loc>{loc}</loc>"]
        if extra == "always":
            out.append("    <changefreq>always</changefreq>")
        elif extra:
            out.append(f"    <lastmod>{extra}</lastmod>")
        out += ["  </url>", ""]
    out += ["</urlset>", ""]
    return "\n".join(out)


def check_posts(posts):
    """Every date a post page states must match the list in blog.html.

    Four copies of each date exist by design — the list, the feeds, the post's
    dateline and the post's BlogPosting node. The first two cannot disagree
    (one is generated from the other); these are the two that could.
    """
    problems = []
    for p in posts:
        text = (PERSONAL / p["href"]).read_text(encoding="utf-8")

        dateline = re.search(r'<p class="dateline">(.*?)</p>', text, re.S)
        if not dateline:
            problems.append(f'{p["href"]}: no <p class="dateline">')
        else:
            seen = re.findall(r'datetime="(\d{4}-\d{2}-\d{2})"',
                              dateline.group(1))
            want = [p["published"]] + ([p["updated"]]
                                       if p["updated"] != p["published"] else [])
            if seen != want:
                problems.append(
                    f'{p["href"]}: dateline says {seen}, blog.html says {want}')

        for prop in ("datePublished", "dateModified"):
            want = p["published"] if prop == "datePublished" else p["updated"]
            found = re.findall(rf'"{prop}": "([^"]*)"', text)
            if found != [want]:
                problems.append(
                    f'{p["href"]}: JSON-LD {prop} is {found}, expected ["{want}"]')

        # The og:type/article:*_time pair mirrors the same two dates.
        for prop, want in (("article:published_time", p["published"]),
                           ("article:modified_time", p["updated"])):
            m = re.search(rf'<meta property="{prop}" content="([^"]*)"', text)
            if not m or m.group(1) != want:
                problems.append(
                    f'{p["href"]}: {prop} is '
                    f'{m.group(1) if m else "missing"}, expected {want}')
    return problems


def jsonld_blocks():
    """Every JSON-LD block in rootdomain/, parsed. Raises PostError on bad JSON.

    Parsing is checked first and separately because it is the failure that
    hurts most: a block with a stray comma is not a degraded result, it is
    silently no structured data at all.
    """
    blocks, problems = [], []
    for path in sorted((ROOT / "rootdomain").rglob("*.html")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for raw in re.findall(
                r'<script[^>]*type="application/ld\+json"[^>]*>(.*?)</script>',
                text, re.S):
            try:
                blocks.append((path.relative_to(ROOT), json.loads(raw)))
            except ValueError as exc:
                problems.append(f"{path.relative_to(ROOT)}: bad JSON-LD: {exc}")
    if problems:
        raise PostError("\n           ".join(problems))
    return blocks


def check_graph(blocks):
    """No @id may be referenced without being defined somewhere on the site.

    The site's structured data is ONE graph split across documents and joined
    by @id, so a node can legitimately be a bare {"@id": ...} reference on the
    page that mentions it and be described on the page that owns it. The cost
    of that design is exactly this failure: a typo in an @id, or a node whose
    owning page dropped it, leaves a reference pointing at nothing — and it is
    invisible from any single page, which is why nothing else can catch it.

    A node is "defined" by carrying an @type alongside its @id; that is the
    same test the identity-only restatements pass, which is intended. This
    checks that the graph joins up, not how much each document says.
    """
    defined, refs = set(), {}

    def walk(node, src):
        if isinstance(node, list):
            for item in node:
                walk(item, src)
        elif isinstance(node, dict):
            ident = node.get("@id")
            if ident:
                (defined.add(ident) if "@type" in node
                 else refs.setdefault(ident, src))
            for key, value in node.items():
                if key != "@id":
                    walk(value, src)

    for src, doc in blocks:
        walk(doc, src)
    return [f"{src}: @id {ident} is referenced but defined nowhere"
            for ident, src in sorted(refs.items()) if ident not in defined]


def main():
    check = "--check" in sys.argv[1:]

    try:
        posts = parse_posts(BLOG.read_text(encoding="utf-8"))
    except (PostError, OSError) as exc:
        print(f"makeMeta: {exc}", file=sys.stderr)
        return 1

    try:
        blocks = jsonld_blocks()
    except PostError as exc:
        print(f"makeMeta: {exc}", file=sys.stderr)
        return 1

    problems = check_posts(posts) + check_graph(blocks)
    if problems:
        for line in problems:
            print(f"makeMeta: {line}", file=sys.stderr)
        return 1

    blog_text = BLOG.read_text(encoding="utf-8")
    start, end = blog_text.find(START), blog_text.find(END)
    if start < 0 or end < 0:
        print("makeMeta: blogld markers missing from blog.html", file=sys.stderr)
        return 1
    new_blog = blog_text[:start] + blog_ld(posts) + blog_text[end + len(END):]

    stale = []
    for path, text in ((BLOG, new_blog), (OUT_SITEMAP, sitemap(posts))):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if check:
            stale.append(path.name)
        else:
            path.write_text(text, encoding="utf-8")
            print(f"makeMeta: wrote {path.relative_to(ROOT)}")

    if stale:
        print(f"makeMeta: out of date: {', '.join(stale)} "
              f"— run assetsBuild/makeMeta.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
